export const sourceReferences: Record<string,string> = {
  "https://pubmed.ncbi.nlm.nih.gov/18832647/": "Whitson & Galinsky (2008) — Lacking control increases illusory pattern perception",
  "https://pmc.ncbi.nlm.nih.gov/articles/PMC6650473/": "Rocher et al. (2019) — Re-identification in incomplete datasets",
  "https://ics.uci.edu/~gmark/chi08-mark.pdf": "Mark et al. (2008) — The Cost of Interrupted Work: More Speed and Stress",
  "https://www.microsoft.com/en-us/research/wp-content/uploads/2016/10/p903-mark.pdf": "Mark et al. (2015) — Focused, Aroused, but so Distractible: A Temporal Perspective on Multitasking and Communications",
  "https://www.nature.com/articles/s41562-018-0506-1": "Orben & Przybylski (2019) — Digital technology use and adolescent well-being",
  "https://journals.sagepub.com/doi/10.1177/2167702617723376": "Twenge et al. (2018) — Adolescent depressive symptoms and screen time",
  "https://www.nature.com/articles/nrn2787": "Friston (2010) — The free-energy principle: a unified brain theory?",
  "https://www.sciencedirect.com/science/article/abs/pii/S0022537177800121": "Hasher et al. (1977) — Frequency and the conference of referential validity",
  "https://www.apa.org/pubs/journals/features/xge-0000098.pdf": "Fazio et al. (2015) — Knowledge does not protect against illusory truth",
  "https://www.sciencedirect.com/science/article/abs/pii/0364021388900237": "Sweller (1988) — Cognitive load during problem solving: Effects on learning",
  "https://www2.psych.ubc.ca/~schaller/528Readings/Festinger1954.pdf": "Festinger (1954) — A theory of social comparison processes",
  "https://pages.nist.gov/frvt/": "NIST — Face Technology Evaluations: FRTE/FATE",
  "https://arxiv.org/abs/2210.08402": "Schuhmann et al. (2022) — LAION-5B dataset",
  "https://behaviormodel.org/": "BJ Fogg — Behavior Model (авторска рамка)",
  "https://www.nirandfar.com/hooked/": "Nir Eyal — Hooked (книга за продуктов дизайн)",
  "https://www.humanetech.com/": "Center for Humane Technology — застъпническа организация",
  "https://digital-strategy.ec.europa.eu/en/policies/digital-services-act": "Европейска комисия — Digital Services Act",
  "https://eur-lex.europa.eu/eli/reg/2022/2065/oj/eng": "EUR-Lex — Регламент (ЕС) 2022/2065",
  "https://www.esafety.gov.au": "eSafety Commissioner — официален регулатор",
  "https://pubmed.ncbi.nlm.nih.gov/9054347/": "Schultz W (1997) — A neural substrate of prediction and reward",
  "https://pubmed.ncbi.nlm.nih.gov/17907866/": "Wood W (2007) — A new look at habits and the habit-goal interface",
  "https://pubmed.ncbi.nlm.nih.gov/12605077/": "Baumeister RF (2003) — Ego depletion and self-regulation failure: a resource model of self-control",
  "https://pubmed.ncbi.nlm.nih.gov/27474142/": "Hagger MS (2016) — A Multilab Preregistered Replication of the Ego-Depletion Effect",
  "https://pubmed.ncbi.nlm.nih.gov/25408384/": "Deb A (2015) — Phantom vibration and phantom ringing among mobile phone users: A systematic review of literature",
  "https://pubmed.ncbi.nlm.nih.gov/36445195/": "Ramasubramani P (2023) — Prevalence of Phantom Vibrations and Ringing Syndrome, and its Association with Smartphone Addiction among Medical Students of Teaching Hospital, South",
  "https://pubmed.ncbi.nlm.nih.gov/34563980/": "Valkenburg PM (2022) — Social media use and its impact on adolescent mental health: An umbrella review of the evidence",
  "https://pubmed.ncbi.nlm.nih.gov/20980228/": "Bridges AJ (2010) — Aggression and sexual behavior in best-selling pornography videos: a content analysis update",
  "https://pmc.ncbi.nlm.nih.gov/articles/PMC5171207/": "Berridge KC (2016) — Liking, wanting, and the incentive-sensitization theory of addiction",
  "https://pmc.ncbi.nlm.nih.gov/articles/PMC4115664/": "Carter EC (2014) — Publication bias and the limited strength model of self-control: has the evidence for ego depletion been overestimated?",
  "https://pmc.ncbi.nlm.nih.gov/articles/PMC10524518/": "Menon V (2023) — 20 years of the default mode network: A review and synthesis",
  "https://pmc.ncbi.nlm.nih.gov/articles/PMC4410786/": "Beaty RE (2014) — Creativity and the default network: A functional connectivity analysis of the creative brain at rest",
  "https://pmc.ncbi.nlm.nih.gov/articles/PMC5490683/": "Poerio GL (2017) — The role of the default mode network in component processes underlying the wandering mind",
  "https://pmc.ncbi.nlm.nih.gov/articles/PMC6149296/": "Mangot AG (2018) — Prevalence and Pattern of Phantom Ringing and Phantom Vibration among Medical Interns and their Relationship with Smartphone Use and Perceived"
};
