import { useEffect, useRef, useState } from 'react';
import Icon from '@/components/base/Icon';
import { useClassroom } from './ClassroomContext';
import { PostMedia } from './PostCard';
import PostComposer from './PostComposer';
import type { AppId, FocusSettings, Platform, SettingKey } from '../focus/model';
import type { LabApp } from '@/lib/classroom';
import './classroom.css';

export default function NativeUtilities({ appId, platform, settings, onSettingChange, onDarkChange }: {
  appId:AppId;platform:Platform;settings:FocusSettings;onSettingChange:(key:SettingKey)=>void;onDarkChange:(value:boolean)=>void;
}) {
  const lab=useClassroom()!;
  const [page,setPage]=useState<SettingKey|null>(null);
  const [query,setQuery]=useState('');
  const [searched,setSearched]=useState(false);
  const [selected,setSelected]=useState<string|null>(null);
  const [file,setFile]=useState<File|null>(null);
  const [destination,setDestination]=useState<LabApp>('instagram');
  const [cameraMode,setCameraMode]=useState('Снимка');
  const input=useRef<HTMLInputElement>(null);
  useEffect(()=>{onDarkChange(appId==='camera');return()=>onDarkChange(false);},[appId,onDarkChange]);
  const titles:Record<SettingKey,string>=platform==='ios'
    ?{grayscale:'Филтри за цвят',quietNotifications:'Фокус',pauseSocial:'Екранно време'}
    :{grayscale:'Режим „Сън“',quietNotifications:'Не безпокойте',pauseSocial:'Таймери за приложения'};
  const settingsRoot=<div className="lab-system-settings"><h2>Настройки</h2><div className="lab-settings-account"><Icon name="ri-user-line" size={33}/><span>{lab.state.access!.alias}<small>Учебен телефон</small></span></div>{(['grayscale','quietNotifications','pauseSocial'] as const).map(key=><button type="button" key={key} onClick={()=>setPage(key)}><Icon name={key==='grayscale'?'ri-contrast-2-line':key==='quietNotifications'?'ri-focus-3-line':'ri-time-line'} size={23}/><strong>{platform==='ios'&&key==='grayscale'?'Достъпност':platform==='android'&&key==='grayscale'?'Режими и рутини':titles[key]}</strong><Icon name="ri-arrow-right-line" size={18}/></button>)}<p className="lab-muted">Настройките се прилагат върху учебния телефон.</p></div>;
  let body;
  if(appId==='settings')body=page?<div className="lab-system-settings"><button type="button" className="lab-back" onClick={()=>setPage(null)}><Icon name="ri-arrow-left-line" size={20}/>Настройки</button><h2>{titles[page]}</h2><button type="button" role="switch" aria-checked={settings[page]} onClick={()=>onSettingChange(page)}><strong>{page==='grayscale'?'Сиви цветове':page==='quietNotifications'?'Тихи известия':'Пауза на социалните приложения'}</strong><span className={'demo-switch '+(settings[page]?'on':'')} aria-hidden="true"/></button><p className="lab-muted">{page==='grayscale'?'Цветовете се променят. Публикациите и редът им се запазват.':page==='quietNotifications'?'Новите съобщения продължават да се записват, но известията и значките са тихи.': 'Социалните приложения се поставят на пауза. Пощата и чатовете остават достъпни.'}</p></div>:settingsRoot;
  else if(appId==='chrome')body=<div className="lab-browser"><div className="lab-browser-bar"><button type="button" aria-label="Назад в учебния браузър" onClick={()=>{setSelected(null);setSearched(false);}}><Icon name="ri-arrow-left-line" size={20}/></button><span><Icon name="ri-lock-line" size={13}/> budimse.online · занимание</span></div><div className="demo-google-word" aria-label="Учебно търсене"><span style={{color:'#4285f4'}}>Търсене</span></div><form onSubmit={event=>{event.preventDefault();setSearched(true);setSelected(null);}}><label className="demo-search"><Icon name="ri-search-line" size={19}/><input aria-label="Търси в учебното занимание" value={query} placeholder="Търси в заниманието" onChange={event=>setQuery(event.target.value)}/><button type="submit" aria-label="Търси"><Icon name="ri-send-plane-line" size={18}/></button></label></form>{selected ? lab.state.posts.filter(post=>post.id===selected).map(post=><article className="lab-search-result" key={post.id}><strong>{post.alias}</strong><p>{post.content}</p><PostMedia post={post}/></article>) : searched ? lab.state.posts.filter(post=>post.approved&&(post.content+' '+post.alias).toLowerCase().includes(query.toLowerCase())).map(post=><button type="button" className="lab-search-result" key={post.id} onClick={()=>setSelected(post.id)}><small>{post.app_id} · {post.alias}</small><strong>{post.content.slice(0,90)||'Публикация със снимка'}</strong><p>{post.content.slice(90,200)}</p></button>) : <p className="lab-muted">Търси в публикациите на заниманието.</p>}</div>;
  else if(appId==='photos')body=<><h2 className="demo-section-title">{platform==='ios'?'Снимки':'Галерия'}</h2><p className="lab-muted">Снимки и клипове, споделени в заниманието.</p><div className="demo-photo-grid">{lab.state.posts.filter(post=>post.media).map(post=><button type="button" key={post.id} aria-label={'Отвори снимката на '+post.alias} onClick={()=>setSelected(post.id)}><PostMedia post={post} playable={false}/></button>)}</div>{selected&&<div className="lab-sheet" role="dialog" aria-label="Снимка"><header><button type="button" aria-label="Назад към галерията" onClick={()=>setSelected(null)}><Icon name="ri-arrow-left-line" size={23}/></button><strong>Галерия</strong></header><div className="lab-sheet-body">{lab.state.posts.filter(post=>post.id===selected).map(post=><div key={post.id}><PostMedia post={post}/><p className="lab-post-copy">{post.alias} · {post.content}</p></div>)}</div></div>}</>;
  else body=<div className="lab-camera-screen"><div className="lab-camera-placeholder"><Icon name="ri-camera-line" size={75}/><p>Натисни бутона, за да избереш файл или да отвориш камерата на устройството.</p></div><div className="demo-camera-modes">{['Видео','Снимка'].map(mode=><button type="button" key={mode} aria-pressed={cameraMode===mode} onClick={()=>setCameraMode(mode)}>{mode}</button>)}</div><button type="button" className="demo-shutter" aria-label={cameraMode==='Видео'?'Избери или заснеми видео':'Избери или заснеми снимка'} onClick={()=>input.current?.click()}/><input hidden ref={input} type="file" capture="environment" accept={cameraMode==='Видео'?'video/mp4,video/webm':'image/jpeg,image/png,image/webp'} onChange={event=>{setFile(event.target.files?.[0]??null);event.target.value='';}}/>{file&&<div className="lab-sheet" role="dialog" aria-label="Преглед на заснетия файл"><header><button type="button" aria-label="Затвори прегледа" onClick={()=>setFile(null)}><Icon name="ri-arrow-left-line" size={23}/></button><strong>Сподели в заниманието</strong></header><div className="lab-sheet-body"><label className="lab-destination">Приложение<select aria-label="Приложение за публикуване" value={destination} onChange={event=>setDestination(event.target.value as LabApp)}>{['instagram','tiktok','facebook','youtube','x','snapchat'].map(id=><option key={id} value={id}>{id}</option>)}</select></label><PostComposer key={destination} appId={destination} kind={file.type.startsWith('video/')?'clip':'post'} initialFile={file} onClose={()=>setFile(null)}/></div></div>}</div>;
  return <div className={'demo-app lab-native '+(appId==='camera'?'dark':'')} data-testid={'app-'+appId}><div className="demo-app-content">{body}</div></div>;
}
