/**
 * Icon component — wraps lucide-react icons.
 * Maps legacy ri-* className strings to lucide-react components.
 * Usage: <Icon name="ri-mail-line" className="text-gray-500" size={18} />
 */
import {
  Mail, MapPin, ArrowRight, ArrowLeft, ArrowDown, ArrowUp, Calendar, Barcode, History, BellOff,
  ChevronDown, ChevronRight, ChevronLeft, ChevronUp, Menu, X,
  ShieldCheck, Book, BookOpen, Newspaper, Building, Building2,
  School, Home, Mic, Globe, Clock, RefreshCw, Plus, Save,
  Pencil, Trash2, LogOut, User, Users, Lock, Eye, EyeOff,
  Flag, MessageCircle, Heart, Share2, Download, ExternalLink,
  Inbox, FileText, Brain, Contrast, Instagram, Facebook,
  Music, Gamepad2, Repeat, Focus, Wrench, AlertTriangle,
  AlertCircle, CheckCircle2, CheckCircle, Loader2, Star,
  Flame, LayoutDashboard, Reply, Linkedin, Bookmark, File,
  Folder, BookMarked, HeartPulse, Search, Send, Info, HelpCircle,
  Minus, StarIcon, Truck, Shield,
  CreditCard, FlaskConical, Radar, MailOpen, Frown, Home as HomeIcon,
  BarChart2, Video, Smartphone, Camera, Image as ImageIcon, Settings,
  Wifi, Bluetooth, Battery, Bell, Phone, MessageSquare, Compass,
  LayoutGrid, Laptop, ThumbsUp, BadgeCheck, MoreVertical,
  Landmark, Bot, RotateCcw, Shuffle as ShuffleIcon, Trophy, Lightbulb,
  Store,
  Footprints, Smile, Gift, TextQuote,
  type LucideIcon,
} from 'lucide-react';
import { type HTMLAttributes } from 'react';

const iconMap: Record<string, LucideIcon> = {
  'ri-arrow-up-line': ArrowUp,
  'ri-barcode-line': Barcode,
  'ri-calendar-line': Calendar,
  'ri-chat-1-fill': MessageCircle,
  'ri-file-text-line': FileText,
  'ri-history-line': History,
  'ri-notification-off-line': BellOff,
  'ri-repeat-fill': Repeat,
  'ri-mail-line': Mail,
  'ri-mail-open-line': Mail,
  'ri-map-pin-line': MapPin,
  'ri-arrow-right-line': ArrowRight,
  'ri-arrow-left-line': ArrowLeft,
  'ri-arrow-down-s-line': ChevronDown,
  'ri-arrow-up-s-line': ChevronUp,
  'ri-arrow-right-s-line': ChevronRight,
  'ri-arrow-left-s-line': ChevronLeft,
  'ri-arrow-down-line': ArrowDown,
  'ri-menu-line': Menu,
  'ri-close-line': X,
  'ri-shield-check-line': ShieldCheck,
  'ri-book-line': Book,
  'ri-book-open-line': BookOpen,
  'ri-newspaper-line': Newspaper,
  'ri-building-line': Building,
  'ri-building-2-line': Building2,
  'ri-school-line': School,
  'ri-home-4-line': Home,
  'ri-home-line': Home,
  'ri-mic-line': Mic,
  'ri-global-line': Globe,
  'ri-time-line': Clock,
  'ri-refresh-line': RefreshCw,
  'ri-add-line': Plus,
  'ri-save-line': Save,
  'ri-edit-line': Pencil,
  'ri-delete-bin-line': Trash2,
  'ri-delete-bin-2-line': Trash2,
  'ri-logout-box-line': LogOut,
  'ri-user-line': User,
  'ri-user-fill': User,
  'ri-team-line': Users,
  'ri-lock-line': Lock,
  'ri-eye-line': Eye,
  'ri-eye-off-line': EyeOff,
  'ri-flag-line': Flag,
  'ri-chat-1-line': MessageCircle,
  'ri-heart-line': Heart,
  'ri-heart-fill': Heart,
  'ri-share-forward-line': Share2,
  'ri-download-2-line': Download,
  'ri-external-link-line': ExternalLink,
  'ri-inbox-line': Inbox,
  'ri-file-list-3-line': FileText,
  'ri-brain-line': Brain,
  'ri-contrast-2-line': Contrast,
  'ri-instagram-line': Instagram,
  'ri-facebook-fill': Facebook,
  'ri-music-2-fill': Music,
  'ri-gamepad-line': Gamepad2,
  'ri-repeat-line': Repeat,
  'ri-focus-3-line': Focus,
  'ri-tools-line': Wrench,
  'ri-alarm-warning-line': AlertTriangle,
  'ri-error-warning-line': AlertCircle,
  'ri-checkbox-circle-line': CheckCircle2,
  'ri-checkbox-circle-fill': CheckCircle,
  'ri-loader-4-line': Loader2,
  'ri-star-line': Star,
  'ri-fire-line': Flame,
  'ri-dashboard-line': LayoutDashboard,
  'ri-reply-line': Reply,
  'ri-linkedin-line': Linkedin,
  'ri-shopping-bag-line': Bookmark,
  'ri-article-line': FileText,
  'ri-draft-line': File,
  'ri-folder-line': Folder,
  'ri-graduation-cap-line': BookMarked,
  'ri-heart-pulse-line': HeartPulse,
  'ri-search-line': Search,
  'ri-send-plane-line': Send,
  'ri-information-line': Info,
  'ri-question-line': HelpCircle,
  'ri-subtract-line': Minus,
  'ri-star-fill': StarIcon,
  'ri-home-heart-line': HomeIcon,
  'ri-truck-line': Truck,
  'ri-shield-line': Shield,
  'ri-shield-keyhole-line': Shield,
  'ri-secure-payment-line': CreditCard,
  'ri-flask-line': FlaskConical,
  'ri-radar-line': Radar,
  'ri-mail-send-line': MailOpen,
  'ri-emotion-sad-line': Frown,
  'ri-focus-2-line': Focus,
  'ri-group-line': Users,
  'ri-bar-chart-line': BarChart2,
  'ri-youtube-fill': Video,
  'ri-youtube-line': Video,
  'ri-twitter-x-fill': MessageSquare,
  'ri-twitter-x-line': MessageSquare,
  'ri-snapchat-fill': MessageCircle,
  'ri-snapchat-line': MessageCircle,
  'ri-whatsapp-fill': MessageCircle,
  'ri-whatsapp-line': MessageCircle,
  'ri-chrome-fill': Globe,
  'ri-chrome-line': Globe,
  'ri-image-fill': ImageIcon,
  'ri-image-line': ImageIcon,
  'ri-camera-fill': Camera,
  'ri-camera-line': Camera,
  'ri-settings-3-fill': Settings,
  'ri-settings-3-line': Settings,
  'ri-settings-fill': Settings,
  'ri-settings-line': Settings,
  'ri-verified-badge-fill': BadgeCheck,
  'ri-verified-badge-line': BadgeCheck,
  'ri-more-2-fill': MoreVertical,
  'ri-more-2-line': MoreVertical,
  'ri-more-fill': MoreVertical,
  'ri-more-line': MoreVertical,
  'ri-video-line': Video,
  'ri-video-fill': Video,
  'ri-compass-line': Compass,
  'ri-compass-fill': Compass,
  'ri-messenger-fill': MessageCircle,
  'ri-messenger-line': MessageCircle,
  'ri-store-2-line': Store,
  'ri-store-2-fill': Store,
  'ri-notification-line': Bell,
  'ri-notification-fill': Bell,
  'ri-notification-3-fill': Bell,
  'ri-notification-3-line': Bell,
  'ri-notification-4-fill': Bell,
  'ri-notification-4-line': Bell,
  'ri-thumb-up-line': ThumbsUp,
  'ri-thumb-up-fill': ThumbsUp,
  'ri-wifi-fill': Wifi,
  'ri-wifi-line': Wifi,
  'ri-signal-wifi-fill': Wifi,
  'ri-signal-wifi-line': Wifi,
  'ri-bluetooth-fill': Bluetooth,
  'ri-bluetooth-line': Bluetooth,
  'ri-battery-fill': Battery,
  'ri-battery-line': Battery,
  'ri-phone-fill': Phone,
  'ri-phone-line': Phone,
  'ri-message-3-fill': MessageSquare,
  'ri-message-3-line': MessageSquare,
  'ri-apps-fill': LayoutGrid,
  'ri-apps-line': LayoutGrid,
  'ri-safari-fill': Compass,
  'ri-safari-line': Compass,
  'ri-android-fill': Smartphone,
  'ri-android-line': Smartphone,
  'ri-apple-fill': Laptop,
  'ri-apple-line': Laptop,
  'ri-bookmark-fill': Bookmark,
  'ri-bookmark-line': Bookmark,
  'ri-trophy-line': Trophy,
  'ri-trophy-fill': Trophy,
  'ri-shuffle-line': ShuffleIcon,
  'ri-shuffle-fill': ShuffleIcon,
  'ri-check-line': CheckCircle,
  'ri-check-fill': CheckCircle,
  'ri-robot-line': Bot,
  'ri-robot-fill': Bot,
  'ri-restart-line': RotateCcw,
  'ri-restart-fill': RotateCcw,
  'ri-lightbulb-line': Lightbulb,
  'ri-lightbulb-fill': Lightbulb,
  'ri-earth-fill': Globe,
  'ri-earth-line': Globe,
  'ri-smartphone-line': Smartphone,
  'ri-smartphone-fill': Smartphone,
  'ri-government-line': Landmark,
  'ri-government-fill': Landmark,
  'ri-user-follow-line': User,
  'ri-user-follow-fill': User,
  'ri-heart-3-line': Heart,
  'ri-heart-3-fill': Heart,
  'ri-share-forward-fill': Share2,
  'ri-links-line': ExternalLink,
  'ri-run-line': Footprints,
  'ri-emotion-happy-line': Smile,
  'ri-emotion-normal-line': Smile,
  'ri-gift-line': Gift,
  'ri-double-quotes-l': TextQuote,
  'ri-double-quotes-line': TextQuote,
  'ri-quote-left': TextQuote,
};

interface IconProps extends HTMLAttributes<SVGElement> {
  name: string;
  size?: number;
  strokeWidth?: number;
}

export default function Icon({ name, size = 16, strokeWidth = 1.75, className = '', ...rest }: IconProps) {
  const LucideComponent = iconMap[name];

  if (!LucideComponent) {
    return (
      <span
        className={`inline-block w-4 h-4 ${className}`}
        title={`Missing icon: ${name}`}
      />
    );
  }

  return (
    <LucideComponent
      size={size}
      strokeWidth={strokeWidth}
      className={className}
      {...(rest as Parameters<LucideIcon>[0])}
    />
  );
}