// Generated by scripts/build-methodology.py; update through the generator.
const resource = {
  "title": "Методология „Будим се“",
  "version": "2.1",
  "publishedAt": "2026-10-09",
  "dateLabel": "9 октомври 2026 г.",
  "pages": 46,
  "bytes": 239413,
  "href": "/resources/metodologiya-budim-se-v2-1.pdf",
  "worksheetPages": "39-44",
  "worksheets": 6,
  "sections": {
    "caseStudy": "15-16",
    "socialPosts": "20-23",
    "course": "28",
    "lesson": "29",
    "assessment": "33-38"
  },
  "sha256": "087c0b41583111039ec9fd9f84998619fdfe66fe1053e3a92cbc0d60ab5a06e5",
  "studentPack": {
    "title": "Казуси и работни листове",
    "pages": 13,
    "href": "/resources/uchenicheski-paket-budim-se-v2-1.pdf",
    "bytes": 103890,
    "sha256": "f562f19d742dcad74c7b220d80c1724c0e51a2e6baeb7b6f04be837d5f681343",
    "worksheetPages": "8-13"
  }
} as const;

export default resource;
