import { StrictMode } from 'react';
import { createRoot, hydrateRoot } from 'react-dom/client';
import './index.css';
import App from './App';
const root = document.getElementById('root')!;
const app = <StrictMode><App /></StrictMode>;
const renderedRoute = root.dataset.prerenderRoute;
const requestedRoute = location.pathname.replace(/\/$/, '') || '/';
if (root.hasChildNodes() && (!renderedRoute || renderedRoute === requestedRoute)) hydrateRoot(root, app);
else createRoot(root).render(app);
